### ISSUE TITLE
当客户端发送消息过快的时候，客户端和服务端的记录对不上

### ISSUE THREAD

**Issue by TQCasey** [OpenIMSDK/openim-sdk-core#14]
环境，mac系统本地server，3月20号pull的代码

当客户端发送消息过快的时候，客户端和服务端的记录对不上，非常容易复现，发送其实是本地添加记录，本地客户端可能出现未读情况，而对方看不到消息，（但是奇怪的是，重新拉取服务器的记录时，却少了数据，查看数据seq序列是连续的）

**Comment by TQCasey** [comment]
需要详细的复原数据，可以回复一下，应该是逻辑错误，我可以自己修改这个逻辑

**Comment by skiffer-git** [comment]
Can I add your Wechat?
