### ISSUE TITLE
Bug: test error---sendAndWaitResp

### ISSUE THREAD

**Issue by hanzhixiao** [OpenIMSDK/openim-sdk-core#182]
### What happened?

![image](https://github.com/OpenIMSDK/openim-sdk-core/assets/68671759/13d203d9-40a5-4a21-bf74-e8f7333fe53a)
{"level":"ERROR","time":"2023-07-28 17:52:11.816","logger":"sdk","caller":"interaction/long_conn_mgr.go:320","msg":"sendAndWaitResp","PID":8676,"operationID":"1690537933266048245","error":"connection closed,conning...: 10000 NetworkError"}

### What did you expect to happen?

return without error

### How can we reproduce it (as minimally and precisely as possible)?

![image](https://github.com/OpenIMSDK/openim-sdk-core/assets/68671759/99252553-c413-47d4-ac55-95e9aec611aa)
run this test function to recall the issu

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by FGadvancer** [comment]
It appears to be a bug in the load testing program where a for loop coroutine is causing duplicate user IDs.
