### ISSUE TITLE
如何编译出给electron使用

### ISSUE THREAD

**Issue by tangjiaqq** [OpenIMSDK/openim-sdk-core#27]
如何编译出给electron使用

**Comment by lstoars** [comment]
你好，解决了吗

**Comment by tangjiaqq** [comment]
无从下手 makefile里面也没

**Comment by lstoars** [comment]
我刚刚搞定了，切换到 ws_wrapper/cmd目录下， 我电脑是mac 
执行  go build open_im_sdk_my.go  生成mac 的程序
执行 CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build open_im_sdk_my.go 生成Windows 程序

不过还没有尝试，是不是用open_im_sdk_my.go  这个文件. 

目前生成出来的mac 版本的打开之后跟web demo 下用的localWs_mac 在控制台的输出是一样的

**Comment by tangjiaqq** [comment]
我去试试 还有一个疑问   生成之后   webdemo 怎么拿到这个可执行文件接收到的消息  回调给web 上层
