### ISSUE TITLE
Bug: Cannot send files exceeding 20MB

### ISSUE THREAD

**Issue by DreamerXXT** [OpenIMSDK/openim-sdk-core#284]
### What happened?

Cannot send files exceeding 20MB

### What did you expect to happen?

Can send larger files

### How can we reproduce it (as minimally and precisely as possible)?

1. Entering a Session
2. Select a file that exceeds 20MB in size

### Anything else we need to know?
[log4.txt](https://github.com/OpenIMSDK/openim-sdk-core/files/12436634/log4.txt)
#### I sent this video：
https://github.com/OpenIMSDK/openim-sdk-core/assets/92249516/4732b7b3-477e-46ba-a218-3c8922c0574a

_No response_

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by FGadvancer** [comment]
This bug has been fixed in open-im-server.
