### ISSUE TITLE
Bug: Compiling the Go SDK into an XCFramework is causing errors on Xcode 15.

### ISSUE THREAD

**Issue by QiuYeHong90** [openimsdk/openim-sdk-core#335]
### What would you like to share?

write /var/folders/lx/tjmdy7gd04l2zs94xml_7k7c0000gn/T/gomobile-work-4091188422/ios/iphoneos/OpenIMCore.framework/Versions/A/Headers/Support.objc.h
write /var/folders/lx/tjmdy7gd04l2zs94xml_7k7c0000gn/T/gomobile-work-4091188422/ios/iphoneos/OpenIMCore.framework/Versions/A/Headers/Universe.objc.h
write /var/folders/lx/tjmdy7gd04l2zs94xml_7k7c0000gn/T/gomobile-work-4091188422/ios/iphoneos/OpenIMCore.framework/Versions/A/Headers/ref.h
write /var/folders/lx/tjmdy7gd04l2zs94xml_7k7c0000gn/T/gomobile-work-4091188422/ios/iphoneos/OpenIMCore.framework/Versions/A/Headers/OpenIMCore.h
write /var/folders/lx/tjmdy7gd04l2zs94xml_7k7c0000gn/T/gomobile-work-4091188422/ios/iphoneos/OpenIMCore.framework/Resources/Info.plist
write /var/folders/lx/tjmdy7gd04l2zs94xml_7k7c0000gn/T/gomobile-work-4091188422/ios/iphoneos/OpenIMCore.framework/Versions/A/Modules/module.modulemap
write /var/folders/lx/tjmdy7gd04l2zs94xml_7k7c0000gn/T/gomobile-work-4091188422/iossimulator/iphonesimulator/OpenIMCore.framework/Versions/A/Headers/Support.objc.h
write /var/folders/lx/tjmdy7gd04l2zs94xml_7k7c0000gn/T/gomobile-work-4091188422/iossimulator/iphonesimulator/OpenIMCore.framework/Versions/A/Headers/Universe.objc.h
write /var/folders/lx/tjmdy7gd04l2zs94xml_7k7c0000gn/T/gomobile-work-4091188422/iossimulator/iphonesimulator/OpenIMCore.framework/Versions/A/Headers/ref.h
write /var/folders/lx/tjmdy7gd04l2zs94xml_7k7c0000gn/T/gomobile-work-4091188422/iossimulator/iphonesimulator/OpenIMCore.framework/Versions/A/Headers/OpenIMCore.h
write /var/folders/lx/tjmdy7gd04l2zs94xml_7k7c0000gn/T/gomobile-work-4091188422/iossimulator/iphonesimulator/OpenIMCore.framework/Resources/Info.plist
write /var/folders/lx/tjmdy7gd04l2zs94xml_7k7c0000gn/T/gomobile-work-4091188422/iossimulator/iphonesimulator/OpenIMCore.framework/Versions/A/Modules/module.modulemap
error: cannot compute path of binary 'Path(str: "/private/var/folders/lx/tjmdy7gd04l2zs94xml_7k7c0000gn/T/gomobile-work-4091188422/ios/iphoneos/OpenIMCore.framework/Versions/A/OpenIMCore")' relative to that of '/var/folders/lx/tjmdy7gd04l2zs94xml_7k7c0000gn/T/gomobile-work-4091188422/ios/iphoneos/OpenIMCore.framework'
gomobile: xcodebuild -create-xcframework -framework /var/folders/lx/tjmdy7gd04l2zs94xml_7k7c0000gn/T/gomobile-work-4091188422/ios/iphoneos/OpenIMCore.framework -framework /var/folders/lx/tjmdy7gd04l2zs94xml_7k7c0000gn/T/gomobile-work-4091188422/iossimulator/iphonesimulator/OpenIMCore.framework -framework /var/folders/lx/tjmdy7gd04l2zs94xml_7k7c0000gn/T/gomobile-work-4091188422/iossimulator/iphonesimulator/OpenIMCore.framework -output build/OpenIMCore.xcframework failed: exit status 70

### Additional information

xcode15 环境 编译gomobile  发生错误
GOARCH=arm64 gomobile bind -v -trimpath -ldflags "-s -w" -o build/OpenIMCore.xcframework -target=ios ./open_im_sdk/ ./open_im_sdk_callback/

**Comment by FGadvancer** [comment]
Please try compiling with Xcode 14 or lower version of Xcode.
