### ISSUE TITLE
Bug: Missing msg.AdvancedTextElem assignment in msgHandleByContentType

### ISSUE THREAD

**Issue by zhaolibo1989** [openimsdk/openim-sdk-core#359]
### What happened?

One client sent an AdvancedText message, but the other client received an empty message content.

### What did you expect to happen?

Received complete AdvancedText message.

### How can we reproduce it (as minimally and precisely as possible)?

Send AdvancedText message with CreateAdvancedTextMessage, and print the message from another.

### Anything else we need to know?

Check here <https://github.com/openimsdk/openim-sdk-core/blob/38415b79d6e8ac4238f42cac6e0d6f6ecae192b5/internal/conversation_msg/conversation_msg.go#L799-L802>

### version

<details>
branch: main

commit: 38415b79d6e8ac4238f42cac6e0d6f6ecae192b5
</details>

**Comment by cubxxw** [comment]
thx
