### ISSUE TITLE
Open-IM-SDK-Core/internal/obj_storage/aws.go 修改后不生效

### ISSUE THREAD

**Issue by kenxudk** [OpenIMSDK/openim-sdk-core#38]

**Comment by BaiMoHan** [comment]
可否贴出相关代码的情况, 以及不生效的表现情况, 有利于排查问题

**Comment by kenxudk** [comment]
我添加了<img width="823" alt="image" src="https://user-images.githubusercontent.com/33343488/198005830-98cc53df-6675-49a9-8e9c-6afdda4fe126.png">
然后
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/33343488/198005969-3a83c3fb-e50c-472b-995c-8dcb94002b03.png">
我直接返回不做任何逻辑处理，但是ios请求过来还是之前的代码，返回错误！
`send message error: Optional("operationID[1666773257731], info[==> open_im_sdk/internal/obj_storage.(*AWS).upload()@84: : operation error S3: PutObject, failed to resolve service endpoint, an AWS region is required, but was not found]ef21fd63d85ad6ffacf666dabda7d33a ")`
服务器是拉取了的。

**Comment by BaiMoHan** [comment]
从你描述来看, 如果执行的还是之前的代码逻辑, 考虑以下两种情况
1. 修改sdk后是否重新生成framework并替换
2. 在sdk初始化时配置的obj_storage的配置参数是否将默认的minio修改为aws

**Comment by wolf-leo** [comment]
一样 修改 Open-IM-SDK-Core/internal/obj_storage/minio.go
在upload下打印或者删除整个方法都不生效
客户端请求的、打印的log 还是旧的数据
