### ISSUE TITLE
Feature: Support set "ex" field in Conversation

### ISSUE THREAD

**Issue by elliotkhd** [openimsdk/openim-sdk-core#423]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [OpenIMSDK Slack](https://join.slack.com/t/openimsdk/shared_invite/zt-1tmoj26uf-_FDy3dowVHBiGvLk9e5Xkg) and got positive feedback

### Is this feature request related to a problem?

❎ No

### Problem Description

I got a situation that the user should be able to set msgDestructTime or delete a message for their friends, I'm thinking doing those features by set "ex" field in Conversation. This is the [issue](https://github.com/openimsdk/openim-sdk-core/issues/439) I commited in the flutter_openim_sdk.

### Solution Description

Add a method in sdk to support setting "ex" field, and the _**onConversationChanged**_(or similar name) listener would be notified when the "ex" field changed.

### Benefits

Make it more flexible to add features about conversation

**Comment by AndrewZuo01** [comment]
Have you check update_conversation in server rest api? https://doc.rentsoft.cn/restapi/apis/conversationManagement/updateConversation
