### ISSUE TITLE
 'Open_im_sdkSignalingOperateStream 2.3.4-2.3.5+3

### ISSUE THREAD

**Issue by simanlx** [openimsdk/openim-sdk-core#518]
### What happened?

Swift Compiler Error (Xcode): Cannot find 'Open_im_sdkSignalingUpdateMeetingInfo' in scope
/Users/han/Desktop/openim_enterprise_chat/pack/flutter_openim_sdk-2.3.5+3/ios/Classes/Module/SignalingManager.swift:63:8

Swift Compiler Error (Xcode): Cannot find 'Open_im_sdkSignalingCreateMeeting' in scope
/Users/han/Desktop/openim_enterprise_chat/pack/flutter_openim_sdk-2.3.5+3/ios/Classes/Module/SignalingManager.swift:67:8

Swift Compiler Error (Xcode): Cannot find 'Open_im_sdkSignalingJoinMeeting' in scope
/Users/han/Desktop/openim_enterprise_chat/pack/flutter_openim_sdk-2.3.5+3/ios/Classes/Module/SignalingManager.swift:71:8

Swift Compiler Error (Xcode): Cannot find 'Open_im_sdkSignalingOperateStream' in scope
/Users/han/Desktop/openim_enterprise_chat/pack/flutter_openim_sdk-2.3.5+3/ios/Classes/Module/SignalingManager.swift:75:8

Swift Compiler Error (Xcode): Cannot find 'Open_im_sdkSignalingGetMeetings' in scope
/Users/han/Desktop/openim_enterprise_chat/pack/flutter_openim_sdk-2.3.5+3/ios/Classes/Module/SignalingManager.swift:79:8

Swift Compiler Error (Xcode): Cannot find 'Open_im_sdkSignalingCloseRoom' in scope
/Users/han/Desktop/openim_enterprise_chat/pack/flutter_openim_sdk-2.3.5+3/ios/Classes/Module/SignalingManager.swift:83:8

Swift Compiler Error (Xcode): Cannot find 'Open_im_sdkSignalingSendCustomSignal' in scope
/Users/han/Desktop/openim_enterprise_chat/pack/flutter_openim_sdk-2.3.5+3/ios/Classes/Module/SignalingManager.swift:87:8

Could not build the application for the simulator.
Error launching application on iPhone 12.

### What did you expect to happen?

相关的分支都被移除了吗?  

### How can we reproduce it (as minimally and precisely as possible)?

1

### version

/Users/han/Desktop/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 3.13.4, on macOS 13.4.1 22F770820d darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.13.4 on channel stable at /Users/han/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 367f9ea16b (5 months ago), 2023-09-12 23:27:53 -0500
    • Engine revision 9064459a8b
    • Dart version 3.1.2
    • DevTools version 2.25.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/han/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

### Cloud provider

1

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by FGadvancer** [comment]
This portion belongs to the enterprise edition of the conferencing code and is not available in the open-source branch.
