### ISSUE TITLE
[BUG] No get friend List when import user to group

### ISSUE THREAD

**Issue by mo3et** [openimsdk/openim-sdk-core#574]
### OpenIM Server Version

3.7.1

### Operating System and CPU Architecture

macOS (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

No get friend List when import user to group

**Comment by FGadvancer** [comment]
commit:8deb27d

**Comment by FGadvancer** [comment]
commit: 8deb27d
