### ISSUE TITLE
[BUG]  Gomobile packaging AAR access project error

### ISSUE THREAD

**Issue by liloutest** [openimsdk/openim-sdk-core#645]
### OpenIM SDK Version

3.8.0

### SDK Platform

Android SDK

### Device Model

nova 10 SE, BNE-AL00

### Operating System Version

HarmonyOS 4.2.0

### Bug Description and Steps to Reproduce

I am using gomobile to package the aar access project for the openim sdk core project, and there is an error message indicating runtime. jar: D8: java. lang. PullPointer Exception: Cannon invoice "String. length()" because "<parameter1>" is null

**Comment by FGadvancer** [comment]
It appears to be an Android-level build issue. You can try to emulate the approach used in the [Android-demo](https://github.com/openimsdk/open-im-android-demo) by including the Android SDK and then verify if it runs correctly. If the issue persists, you can submit more detailed information, and I will continue to assist you.

If you need further help, please feel free to reach out.

**Comment by liloutest** [comment]
But I downloaded the Flutter demo project, developed based on Flutter, and made changes to the native Android version of AAR, which caused errors

**Comment by liloutest** [comment]
core-sdk-3.8.0.aar
