### ISSUE TITLE
[BUG] GetAllConversationList failed: disk I/O error: read-only file system

### ISSUE THREAD

**Issue by FGadvancer** [openimsdk/openim-sdk-core#650]
### OpenIM SDK Version

3.8.1-rc.0

### SDK Platform

Android SDK

### Device Model

navo

### Operating System Version

Android 12

### Bug Description and Steps to Reproduce

There may be return error about "disk I/O error: read-only file system", when app call the function of GetAllConversationList.

**Comment by FGadvancer** [comment]
There may be restrictions on the amount of data read from the disk at once. You should consider calling the GetConversationListSplit function to avoid performance issues caused by excessively large data volumes.

**Comment by dbinhua** [comment]
I ran into the same problem, but changed to `GetConversationListSplit` to show a zero pull when pulling history messages. When will the problem be fixed?
