### ISSUE TITLE
[BUG] After addFriend, the requester will not trigger onFriendApplicationAdded.

### ISSUE THREAD

**Issue by zengyun261** [openimsdk/openim-sdk-core#652]
### OpenIM SDK Version

3.8.0

### SDK Platform

Flutter SDK

### Device Model

Emulator

### Operating System Version

Android 14

### Bug Description and Steps to Reproduce

same as a title

**Comment by mo3et** [comment]
Can you tell me more Debug and Error log Details? You can use `about Us -> upload all logs` to get all logs.
