### ISSUE TITLE
[BUG] When sending file-related messages, the local path will be attached, which should be removed.

### ISSUE THREAD

**Issue by Xiaobai-1024** [openimsdk/openim-sdk-core#659]
### OpenIM SDK Version

3.8.0

### OpenIM Server Version

3.8.0

### SDK Platform

Flutter SDK

### Device Model

All

### Operating System Version

All

### Bug Description and Steps to Reproduce

<img width="800" alt="Code" src="https://github.com/user-attachments/assets/6ad6478c-7baa-4a78-818c-df70aa68d816">

**Comment by mo3et** [comment]
thanks for your feedback.
