### ISSUE TITLE
[Other]: synchronous joining of group members is too slow

### ISSUE THREAD

**Issue by withchao** [openimsdk/openim-sdk-core#668]
### What would you like to share?

synchronous joining of group members is too slow

**Comment by std-s** [comment]
The same lock is used during synchronization, resulting in synchronization of only one group. This will not be optimized for the time being.

**Comment by FGadvancer** [comment]
The issue has been fixed in the latest version. Thank you for your previous questions or suggestions for OpenIM, and we look forward to your continued contributions!
