### ISSUE TITLE
[BUG] In the SDK of android and iOS, the nickname avatar in stranger chat, conversation list and historical messages is not up to date.

### ISSUE THREAD

**Issue by wozaihu** [openimsdk/openim-sdk-core#693]
### OpenIM SDK Version

3.8.1

### OpenIM Server Version

3.8.0

### SDK Platform

Android SDK

### Device Model

小米13

### Operating System Version

android13

### Bug Description and Steps to Reproduce

举例：A和B有会话记录，当B通过setSelfInfo修改了自己的昵称和头像，A通过getAllConversationList中的ConversationInfo 和getAdvancedHistoryMessageList 中的Message 获取不到B最新的昵称和头像，导致A显示的总是B旧的昵称和头像，A收到B的新消息时Message中是B新头像和昵称，但退出会话页面重新打开会调用getAdvancedHistoryMessageList，这又只能显示旧的昵称和头像了，这是bug吗，要怎么处理。

备注：
没有在服务端维护好友关系，所以所有人都是陌生人聊天。

**Comment by FGadvancer** [comment]
When strangers are chatting and the conversation changes, the user must actively click on the other user's profile to trigger the conversation and avatar update. This corresponds to the SDK calling the GetUsersInfoWithCache interface.

**Comment by wozaihu** [comment]
> When strangers are chatting and the conversation changes, the user must actively click on the other user's profile to trigger the conversation and avatar update. This corresponds to the SDK calling the GetUsersInfoWithCache interface.

谢谢，解决了我的问题

**Comment by wozaihu** [comment]
> When strangers are chatting and the conversation changes, the user must actively click on the other user's profile to trigger the conversation and avatar update. This corresponds to the SDK calling the GetUsersInfoWithCache interface.

谢谢，解决了我的问题
