### ISSUE TITLE
[BUG?]: Incomplete Message History Display After Private Chat Deletion

### ISSUE THREAD

**Issue by zhaolibo1989** [openimsdk/openim-sdk-core#749]
### What would you like to share?

Title: Incomplete Message History Display After Private Chat Deletion

Steps to Reproduce:
1. Enable the "IsPrivateChat" feature for a conversation between User A and User B.
2. User A sends more than or equal to 20 regular messages to User B. This number is significant as it corresponds to the default query limit used by the app's SDK when fetching historical messages.
3. User B logs in, views the messages, and marks them as read, initiating the burn countdown for the messages.
4. Once the countdown concludes, the messages are deleted from the conversation.
5. User B restarts the app and queries the latest 20 messages of that conversation. Since all the messages have been burned and are in a "deleted" state, they do not appear. The app fails to display or retrieve any messages that were not part of the initial 20 sent by User A, even though they may not have been deleted.

This issue results in an incomplete display of the conversation history after messages have been burned, as the app's SDK does not account for messages beyond the initial 20 in the query, potentially omitting undeleted messages from the user's view.

**Comment by codingOOatOOyi** [comment]
不要用这个项目，垃圾的要死，坑死你，这个项目主打的怎么复杂就怎么来，怎么赚钱就怎么来

**Comment by FGadvancer** [comment]
#773
