### ISSUE TITLE
[BUG] dns error: dial tcp: lookup test.abc.com on [::1]:53: read udp [::1]:65132->[::1]:53: read: connection refused:

### ISSUE THREAD

**Issue by codingOOatOOyi** [openimsdk/openim-sdk-core#775]
### OpenIM SDK Version

3.5.0

### OpenIM Server Version

3.4.2

### SDK Platform

iOS SDK

### Device Model

iphone 8

### Operating System Version

ios16

### Bug Description and Steps to Reproduce

{
    "errMsg": "error *errors.withStack not implement CodeError: ApiPost http.Client.Do failed Post \"https://test.abc.com:30002/user/get_users_info\": dial tcp: lookup test.abc.com on [::1]:53: read udp [::1]:65132->[::1]:53: read: connection refused: 10000 NetworkError",
    "errCode": 10005,
    "data": ""
}
1./openim-sdk-core/# make ios
2.use framework
3.iphone 8 get error
4.how to fix it?

**Comment by codingOOatOOyi** [comment]
test.abc.com is resolved to 192.168.170.130

**Comment by codingOOatOOyi** [comment]
草台班子项目没人管了吗？

**Comment by zhaolibo1989** [comment]
Try to link `libresolv.tbd` to you xcode project. 
![xcode-add-libresolv](https://github.com/user-attachments/assets/f72a3e82-d413-49f5-bfd2-f9a005035001)

In my case, I use go1.20 to build SDK, but build iOS APP failed, until I link with that library.

God bless you, budy.
