### ISSUE TITLE
[BUG] UpdateMsgSenderFaceURLAndSenderNickname failed: no such table

### ISSUE THREAD

**Issue by Ayloss** [openimsdk/openim-sdk-core#783]
### OpenIM SDK Version

3.8.1

### OpenIM Server Version

3.8.1

### SDK Platform

Electron FFI SDK

### Device Model

x64

### Operating System Version

windows 10

### Bug Description and Steps to Reproduce

I'm trying to update a conversation's nickname and faceurl using getUsersInfo, and get this error in sdk logs.
![企业微信截图_1731919777463](https://github.com/user-attachments/assets/92b96010-92b2-47cb-9c00-8416d3f355b7)
The chatlog table name is incorrect.
![企业微信截图_17319810691206](https://github.com/user-attachments/assets/c395a33e-a919-4fea-b0df-2176b7c32e23)

**Comment by FGadvancer** [comment]
#737
