### ISSUE TITLE
[FEATURE REQUEST] opemim client sdk in python

### ISSUE THREAD

**Issue by davidtao212** [openimsdk/openim-sdk-core#799]
### Why this feature?

Currently I'm working on a robot ralated project, in which all robot-related third-party codes are written in python. I want to introduce the openim-sdk in our project to implement the communication between robots or communication between robots and control center.

### Suggested Solution

Could we add a python wapper on openim-sdk-core or is there some tool that can automatically generate python code from openim-sdk-core?
Thanks!

**Comment by davidtao212** [comment]
Thanks for your quick response :-) 
The integration is at client side. Let me add more context, we work on a robot project and want to remote control the robot as well as add messaging function between robot and controller. To achieve this goal, the robot state data, control data, and text messages need to be transmited between robot and controller. After some investigation, we found OpenIM a very suitable framework as the underlying IM infrastructure. Unfortunately, the hardware manufacturer only provide us python SDK to collect state data from robot or control the robot. That's why we want a client side python-sdk to integrate in our project.

**Comment by FGadvancer** [comment]
I'm not sure if my understanding is correct. You also have an operating system on your robot, and the SDK can run on top of it. Your client-side development technology stack is Python for cross-platform, right? So you are looking for a Python SDK. If that's the case, could you tell me what your specific cross-platform solution is?

**Comment by davidtao212** [comment]
Yes, you are right. When you say cross platform solution, do you mean the UI stuff? Actually, at the robot side, we do not need UI. There's a daemon process that collects robot data from hardware and send message to controller when some event happens. Controller side is a linux machine on which a user can send command to the robot. We are planning to use python QT to build the UI. This is the only place where UI is needed, so we don't consider the cross-platform UI such as android/ios apps.

**Comment by FGadvancer** [comment]
Sure, I understand your needs. As you mentioned, PythonQt essentially calls C/C++ interfaces, and sdk-core also provides [C interfaces](https://github.com/openimsdk/openim-sdk-cpp). If you can call the C interfaces yourself, you can integrate sdk-core by compiling the appropriate dynamic libraries for your robot system and directly calling the C interfaces. If you do need a complete Python library, it may take some time, but usually, it's not too difficult since there’s only one layer of communication bridge code in between.

**Comment by skiffer-git** [comment]
If you're using this on an embedded device, [[EMQX](https://www.emqx.com/zh/products/emqx)](https://www.emqx.com/zh/products/emqx) should be able to meet your needs.

**Comment by davidtao212** [comment]
@FGadvancer @skiffer-git Thank you guys for the help!   
I'll try to use the C interface of sdk-core first and also do some investigation on MQTT.
