### ISSUE TITLE
go mod 安装 Open-IM-SDK-Core 不成功

### ISSUE THREAD

**Issue by kevinmiao** [OpenIMSDK/openim-sdk-core#8]
go get github.com/OpenIMSDK/Open-IM-SDK-Core
go get: github.com/OpenIMSDK/Open-IM-SDK-Core@v1.0.7: parsing go.mod:
	module declares its path as: open_im_sdk
	        but was required as: github.com/OpenIMSDK/Open-IM-SDK-Core

go get Open-IM-SDK-Core 安装失败，这种情况应该怎么解决

**Comment by xiaoer105** [comment]
我也遇到了同样的问题，最后有得到解决吗

**Comment by tangjiaqq** [comment]
你们编译成功了吗？

**Comment by leixjin** [comment]
The same error
