### ISSUE TITLE
[BUG] Unable to get voice messages from local messages

### ISSUE THREAD

**Issue by BeiJiu123** [openimsdk/openim-sdk-core#817]
当使用  SearchResult result = await OpenIM.iMManager.messageManager
        .searchLocalMessages(
            conversationID: conversationID,
            messageTypeList: [101, 102, 103, 104, 105],
            keywordList: [],
            searchTimePosition: 0,
            searchTimePeriod: 0,
            pageIndex: pageIndex,
            count: 10); 获取本地消息的时候,可以获取其他类型的信息但是无法获取语音信息,语音信息是成功发送了的,

**Comment by FGadvancer** [comment]
Thank you very much for figure out this issue. It has been fixed and will be included in the update scheduled for release in version 3.8.3 after testing is completed.
